export const RESTORE_SESSION = 'RESTORE_SESSION';

// HTTP Actions Types
export const POST_SUCCESSFUL = 'POST_SUCCESSFUL';
export const POST_FAILED = 'POST_FAILED';
export const GET_SUCCESSFUL = 'GET_SUCCESSFUL';
export const GET_FAILED = 'GET_FAILED';

// Server Requests
export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PREFERENCES = 'UPDATE_PREFERENCES';
export const DELETE_USER = 'DELETE_USER';
export const GET_RECENT_TRADES = 'GET_RECENT_TRADES';
export const CREATE_JOURNAL = 'CREATE_JOURNAL';
export const DELETE_JOURNAL = 'DELETE_JOURNAL';
export const UPDATE_JOURNAL = 'UPDATE_JOURNAL';
export const UPLOAD_PROFILE_PIC = 'UPLOAD_PROFILE_PIC';
export const FETCH_PROFILE_PIC = 'FETCH_PROFILE_PIC';
export const CREATE_TRADE = 'CREATE_TRADE';

// Other
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_JOURNAL_TRADES = 'GET_JOURNAL_TRADES';
export const UPDATE_TRADE = 'UPDATE_TRADE';
export const DELETE_TRADE = 'DELETE_TRADE';
export const SHOW_ERROR = 'SHOW_ERROR';
export const CONTACT_US_MAIL = 'CONTACT_US_MAIL';
