export const FETCH_STATUS = 'FETCH_STATUS';
export const UPDATE_FLAG_STATE = 'UPDATE_FLAG_STATE';
export const RESET_SESSION_RESTORED = 'RESET_SESSION_RESTORED';

// For Error
export const RESET_ERROR_FLAG = 'RESET_ERROR_FLAG';

// For Redirects
export const RESET_LOGIN_REDIRECT = 'RESET_LOGIN_REDIRECT';

export const RESET_DATA_UPDATED = 'RESET_DATA_UPDATED';
export const RESET_DATA_DELETED = 'RESET_DATA_DELETED';
export const RESET_DATA_CREATED = 'RESET_DATA_CREATED';
export const RESET_PROFILE_UPLOAD = 'RESET_PROFILE_UPLOAD';
