export const FETCH_STATUS = "FETCH_STATUS";
export const UPDATE_FLAG_STATE = "UPDATE_FLAG_STATE";
export const RESET_SESSION_RESTORED = "RESET_SESSION_RESTORED";

// For Error
export const RESET_ERROR_FLAG = "RESET_ERROR_FLAG";
